export const skillOptions = [
  'Accountability',
  'Active listening',
  'Adaptability',
  'Agile delivery',
  'AI literacy',
  'Analytical thinking',
  'API design',
  'Attention to detail',
  'Automation',
  'Budgeting',
  'Business analysis',
  'Change management',
  'Coaching',
  'Collaboration',
  'Communication',
  'Conflict resolution',
  'Content strategy',
  'Creativity',
  'Critical thinking',
  'Customer empathy',
  'Customer success',
  'Data analysis',
  'Data visualization',
  'Decision-making',
  'Delegation',
  'Design thinking',
  'Documentation',
  'Emotional intelligence',
  'Experiment design',
  'Facilitation',
  'Financial modelling',
  'Forecasting',
  'Growth strategy',
  'Influence',
  'Leadership',
  'Machine learning',
  'Mentoring',
  'Negotiation',
  'Operations management',
  'Performance management',
  'Presentation',
  'Prioritization',
  'Problem solving',
  'Product discovery',
  'Product management',
  'Project management',
  'Public speaking',
  'Quality assurance',
  'Research',
  'Resilience',
  'Risk management',
  'Sales',
  'Security awareness',
  'Service design',
  'Software engineering',
  'Stakeholder management',
  'Strategic planning',
  'Systems thinking',
  'Technical writing',
  'Time management',
  'UX design',
] as const

export const workTypeOptions = [
  'Analytical work',
  'Creative work',
  'Customer-facing work',
  'Deep focus work',
  'Hands-on execution',
  'Leading teams',
  'Mentoring others',
  'Operational planning',
  'People-facing work',
  'Process improvement',
  'Product strategy',
  'Research and discovery',
  'Solving technical problems',
  'Storytelling and communication',
  'Systems design',
  'Teaching and enablement',
  'Troubleshooting',
  'Writing and documentation',
] as const

export const roleOptions = [
  'Account Manager',
  'Business Analyst',
  'Chief Executive Officer',
  'Chief Financial Officer',
  'Chief Operating Officer',
  'Customer Success Manager',
  'Data Analyst',
  'Data Scientist',
  'Delivery Manager',
  'Design Lead',
  'Engineering Manager',
  'Finance Manager',
  'HR Manager',
  'Marketing Manager',
  'Operations Manager',
  'People Partner',
  'Product Designer',
  'Product Manager',
  'Program Manager',
  'Project Manager',
  'QA Engineer',
  'Sales Manager',
  'Software Engineer',
  'Support Specialist',
  'UX Researcher',
] as const
